### ISSUE TITLE
Data for evidence selection 

### ISSUE THREAD

**Issue by Ro0tee** [asaakyan/covidfact#1]
Hi,

May I know if all gold documents of COVIDFACT can be found in _scraped_docs.json_ and _scraped_docs_additional1k.json_?  It seems gold documents for 13 claims of train.tsv and 1 claim of dev.tsv can't be found in these two file.

Thank you.

**Comment by asaakyan** [comment]
what do you mean can't be found? please try searching files manually as there could be issues with string match. if still not found, please email me a list of claims that were not found and I may be able to look into it.
