### ISSUE TITLE
Python version and uninstallable packages in requirements.txt

### ISSUE THREAD

**Issue by LKChenLK** [asaakyan/covidfact#2]
Hi, could you provide the Python version you used for this project? I was using Python 3.9 when I ran `pip install -r requirements.txt.`, and a lot of packages cannot be installed because of the Python version.

Also, when I strip away the package versions in `requirements.txt`, these below still cannot be installed. Are any of them necessary for the code to run?

```
fail2ban
breezy
fastimport
gpg
iotop
dbus-python
language-selector
PyGObject
python-apt
pycairo 
pycups 
python-ldap
systemd-python
ubuntu-advantage-tools
ufw
unattended-upgrades
```

**Comment by asaakyan** [comment]
they don't seem necessary. please try without them or use python 3.7.
